title: Eleni's Portfolio
author: Eleni
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio as a test. I'll do the real one soon once this nice lil bot teaches me how to code. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
